# Generated by Django 3.2.10 on 2021-12-31 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_alter_property_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='data',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
