# Generated by Django 3.2.10 on 2021-12-31 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_alter_property_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='unique_id',
        ),
    ]
